// Covers the stale-claim commit path that ChatGPT flagged on 2026-09-18.
//
// The local machine cannot reach Atlas (TLS failure under Node 26), so these
// drive commitMessage against a fake that enforces the one thing the real
// guarantee rests on: the unique (sessionId, turnIndex) index.

import test from "node:test";
import assert from "node:assert/strict";
import { commitMessage, reconcileSession } from "../blue-room/database.js";

const SESSION_ID = "68c1f0000000000000000001";

// Minimal stand-in for the two collections commitMessage touches. Supports
// only the query shapes it actually issues; anything else throws loudly
// rather than silently passing a test.
function fakeDb({ session, messages = [] }) {
  const state = { session: { ...session }, messages: [...messages] };

  function matches(doc, filter) {
    return Object.entries(filter).every(([key, want]) => {
      if (key === "_id") return String(doc._id) === String(want);
      return doc[key] === want;
    });
  }

  const sessions = {
    async findOne() {
      return { ...state.session };
    },
    async findOneAndUpdate(filter, update) {
      if (!matches(state.session, filter)) return null;
      Object.assign(state.session, update.$set);
      return { ...state.session };
    },
  };

  const messagesCol = {
    async insertOne(doc) {
      const clash = state.messages.some(
        m => String(m.sessionId) === String(doc.sessionId) && m.turnIndex === doc.turnIndex
      );
      if (clash) {
        const err = new Error("E11000 duplicate key error");
        err.code = 11000;
        throw err;
      }
      state.messages.push({ ...doc });
      return { insertedId: `msg-${state.messages.length}` };
    },
    async countDocuments() {
      return state.messages.length;
    },
    async findOne(filter) {
      return state.messages.find(m => matches(m, filter)) ?? null;
    },
  };

  return {
    state,
    collection(name) {
      if (name === "blue_room_sessions") return sessions;
      if (name === "blue_room_messages") return messagesCol;
      throw new Error(`unexpected collection: ${name}`);
    },
  };
}

function sessionAt(turnIndex, claimId) {
  return {
    _id: SESSION_ID,
    status: "running",
    totalMessages: 20,
    completedMessages: turnIndex,
    nextTurnIndex: turnIndex,
    turnState: "running",
    claimId,
    completedAt: null,
  };
}

// Turn indices are dense — a turn is only ever claimed at nextTurnIndex — and
// reconcileSession relies on that to rebuild counters by counting. So a
// fixture sitting at index N must actually contain messages 0..N-1.
function priorMessages(n) {
  return Array.from({ length: n }, (_, i) => ({
    sessionId: SESSION_ID,
    turnIndex: i,
    speaker: i % 2 === 0 ? "claude" : "openai",
    text: `earlier message ${i}`,
  }));
}

test("the live claim commits normally and is not flagged stale", async () => {
  const db = fakeDb({ session: sessionAt(4, "claim-live"), messages: priorMessages(4) });

  const result = await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
    text: "The corridor light keeps flickering.", claimId: "claim-live", db,
  });

  assert.equal(result.staleWriter, false);
  assert.equal(result.session.completedMessages, 5);
  assert.equal(result.session.nextTurnIndex, 5);
  assert.equal(result.session.turnState, "pending");
  assert.equal(db.state.messages.length, 5);
});

// The race ChatGPT described: an expired claim returns first and wins the
// insert, while the replacement claim owns the session.
test("a stale claim that wins the insert is accepted but reported as stale", async () => {
  // Lease expired; claim-B has taken over the session document.
  const db = fakeDb({ session: sessionAt(4, "claim-B"), messages: priorMessages(4) });

  const stale = await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
    text: "Text generated by the slow, expired claim.", claimId: "claim-A", db,
  });

  // Accepted: the generation is already paid for and was built from exactly
  // the same history claim-B saw, so discarding it would buy nothing.
  assert.equal(db.state.messages[4].text, "Text generated by the slow, expired claim.");
  // ...but surfaced, so a lease expiring mid-flight is measurable.
  assert.equal(stale.staleWriter, true);
  // Counters are still correct despite the lost fence.
  assert.equal(stale.session.completedMessages, 5);
  assert.equal(stale.session.nextTurnIndex, 5);
});

test("the replacement claim is then refused by the unique index, not double-written", async () => {
  const db = fakeDb({ session: sessionAt(4, "claim-B"), messages: priorMessages(4) });

  await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
    text: "From the expired claim.", claimId: "claim-A", db,
  });

  const replacement = await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
    text: "From the replacement claim.", claimId: "claim-B", db,
  });

  assert.equal(replacement.error, "already_committed");
  assert.equal(db.state.messages.length, 5, "a turn must never hold two messages");
  assert.equal(db.state.messages[4].text, "From the expired claim.");
  assert.equal(replacement.session.completedMessages, 5);
});

test("whichever order the two claims return in, exactly one message exists", async () => {
  for (const [first, second] of [["claim-A", "claim-B"], ["claim-B", "claim-A"]]) {
    const db = fakeDb({ session: sessionAt(4, "claim-B"), messages: priorMessages(4) });

    await commitMessage({
      sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
      text: `text from ${first}`, claimId: first, db,
    });
    await commitMessage({
      sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
      text: `text from ${second}`, claimId: second, db,
    });

    assert.equal(db.state.messages.length, 5, `two messages written for order ${first}/${second}`);
    assert.equal(db.state.messages[4].text, `text from ${first}`, "the first writer wins");
  }
});

test("the winning claim is recorded on the message so double generation is auditable", async () => {
  const db = fakeDb({ session: sessionAt(4, "claim-B"), messages: priorMessages(4) });

  await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "claude",
    text: "From the expired claim.", claimId: "claim-A", db,
  });

  assert.equal(db.state.messages[4].claimId, "claim-A");
});

// A crash between the insert and the counter update lands in the same branch
// as a lost fence, and must leave the session usable rather than stuck.
test("counters rebuild from the messages after a crash between the two writes", async () => {
  const db = fakeDb({
    session: { ...sessionAt(2, "claim-x"), completedMessages: 1, nextTurnIndex: 1 },
    messages: [
      { sessionId: SESSION_ID, turnIndex: 0, speaker: "claude",  text: "one" },
      { sessionId: SESSION_ID, turnIndex: 1, speaker: "openai",  text: "two" },
    ],
  });

  const session = await reconcileSession(SESSION_ID, { db });

  assert.equal(session.completedMessages, 2);
  assert.equal(session.nextTurnIndex, 2);
  assert.equal(session.turnState, "pending");
  assert.equal(session.claimId, null);
});

test("reconcile marks a session complete once the last message exists", async () => {
  const messages = Array.from({ length: 20 }, (_, i) => ({
    sessionId: SESSION_ID, turnIndex: i, speaker: i % 2 === 0 ? "claude" : "openai", text: `m${i}`,
  }));
  const db = fakeDb({ session: { ...sessionAt(19, "claim-z"), completedMessages: 19 }, messages });

  const session = await reconcileSession(SESSION_ID, { db });

  assert.equal(session.completedMessages, 20);
  assert.equal(session.status, "completed");
  assert.equal(session.turnState, "completed");
  assert.ok(session.completedAt instanceof Date);
});

test("a commit for the wrong side is refused before any provider text is stored", async () => {
  const db = fakeDb({ session: sessionAt(4, "claim-live"), messages: priorMessages(4) });

  const result = await commitMessage({
    sessionId: SESSION_ID, turnIndex: 4, speaker: "openai",
    text: "openai must not speak on an even index", claimId: "claim-live", db,
  });

  assert.equal(result.error, "speaker_out_of_order");
  assert.equal(db.state.messages.length, 4, "no new message was stored");
});
